apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-build-push
  namespace: cicd
spec:
  serviceAccountName: workflow-runner
  arguments:
    parameters:
      - name: gitrepo
      - name: gitrevision
      - name: gitbefore
      - name: imagename
      - name: imagetag
      - name: watchpath
        value: apps/my-service/app
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: gitrepo
          - name: gitrevision
          - name: gitbefore
          - name: imagename
          - name: imagetag
          - name: watchpath
      steps:
        - - name: detectchanges
            template: detectchanges
            arguments:
              parameters:
                - name: gitrepo
                  value: "{{workflow.parameters.gitrepo}}"
                - name: gitrevision
                  value: "{{workflow.parameters.gitrevision}}"
                - name: gitbefore
                  value: "{{workflow.parameters.gitbefore}}"
                - name: imagename
                  value: "{{workflow.parameters.imagename}}"
                - name: imagetag
                  value: "{{workflow.parameters.imagetag}}"
                - name: watchpath
                  value: "{{inputs.parameters.watchpath}}"
        - - name: build-image
            template: build-image
            arguments:
              parameters:
                - name: gitrepo
                  value: "{{workflow.parameters.gitrepo}}"
                - name: gitrevision
                  value: "{{workflow.parameters.gitrevision}}"
                - name: imagename
                  value: "{{workflow.parameters.imagename}}"
                - name: imagetag
                  value: "{{workflow.parameters.imagetag}}"
            when: "{{steps.detectchanges.outputs.result}} == 'true'"
        - - name: update-values
            template: update-values
            arguments:
              parameters:
                - name: gitrepo
                  value: "{{workflow.parameters.gitrepo}}"
                - name: gitrevision
                  value: "{{workflow.parameters.gitrevision}}"
                - name: gitbefore
                  value: "{{workflow.parameters.gitbefore}}"
                - name: imagename
                  value: "{{workflow.parameters.imagename}}"
                - name: imagetag
                  value: "{{workflow.parameters.imagetag}}"
            when: "{{steps.detectchanges.outputs.result}} == 'true'"
    - name: detectchanges
      inputs:
        parameters:
          - name: gitrepo
          - name: gitrevision
          - name: gitbefore
          - name: imagename
          - name: imagetag
          - name: watchpath
            value: apps/my-service/app
      script:
        image: alpine:3.19
        command: [sh]
        source: |
          #set -euo pipefail
          apk add --no-cache git
          REPO="{{inputs.parameters.gitrepo}}"
          TARGET_RAW="{{inputs.parameters.gitrevision}}"
          BEFORE_RAW="{{inputs.parameters.gitbefore}}"
          imagename="{{inputs.parameters.imagename}}"
          imagenameTAG="{{inputs.parameters.imagetag}}"
          watchpath="{{inputs.parameters.watchpath}}"
          echo "Cloning repo ${REPO}" >&2
          echo "Using tag ${imagenameTAG}" >&2
          echo "Watching path ${watchpath}" >&2
          echo "Watching path ${watchpath}"
          git clone "${REPO}" repo >&2
          cd repo
          ZERO_SHA="0000000000000000000000000000000000000000"
          TARGET="$(printf %s \"${TARGET_RAW}\" | tr -d '\r')"
          BEFORE="$(printf %s \"${BEFORE_RAW}\" | tr -d '\r')"
          echo "Fetched target revision: '$TARGET'" >&2
          echo "Fetched before revision: '$BEFORE'" >&2 
          if [ -z "$TARGET" ] || [ "$TARGET" = "$ZERO_SHA" ]; then
            TARGET="$(git rev-parse origin/HEAD)"
            echo "No target commit specified, using HEAD: $TARGET" >&2
          else
            git fetch origin "$TARGET" >&2 || true
            echo "Using specified target commit: $TARGET" >&2
          fi
          echo "Target commit: $TARGET" >&2
          echo "Before commit: $BEFORE" >&2
          git fetch origin --tags >&2 || true
          git checkout "$TARGET" >&2 || true
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "$ZERO_SHA" ]; then
            if git rev-parse "${TARGET}^" >/dev/null 2>&1; then
              BEFORE="$(git rev-parse "${TARGET}^")"
              echo "No prior commit specified, using parent: $BEFORE" >&2
            else
              echo "No prior commit found, forcing build" >&2
              printf true
              exit 0
            fi
          fi
          echo git diff --name-only "$BEFORE" "$TARGET" >&2
          if git diff --name-only "$BEFORE" "$TARGET" -- $watchpath | grep -q .; then
            echo "Changes detected in $watchpath, proceeding with build." >&2
            printf true
          else
            echo "No changes detected in $watchpath, skipping build." >&2
            printf false
          fi
    - name: build-image
      inputs:
        parameters:
          - name: gitrepo
          - name: gitrevision
          - name: imagename
          - name: imagetag
        artifacts:
          - name: source
            path: /workspace/src
            git:
              repo: "{{inputs.parameters.gitrepo}}"
              revision: "{{inputs.parameters.gitrevision}}"
      container:
        image: gcr.io/kaniko-project/executor:v1.16.0
        command: ["/kaniko/executor"]
        args:
          - "--context=dir:///workspace/src/apps/my-service"
          - "--destination={{inputs.parameters.imagename}}:{{inputs.parameters.imagetag}}"
          - "--dockerfile=Dockerfile"
          - "--snapshotMode=redo"
          - "--cleanup"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: ghcr-creds
            items:
              - key: .dockerconfigjson
                path: config.json
    - name: update-values
      inputs:
        parameters:
          - name: gitrepo
          - name: gitrevision
          - name: imagename
          - name: imagetag
      script:
        image: alpine:3.19
        command: [sh]
        source: |
          set -euo pipefail
          apk add --no-cache git yq
          git clone "{{inputs.parameters.gitrepo}}" repo
          cd repo
          git checkout "{{inputs.parameters.gitrevision}}"
          yq -i ".image.repository = \"{{inputs.parameters.imagename}}\"" apps/my-service/helm/values.yaml
          yq -i ".image.tag = \"{{inputs.parameters.imagetag}}\"" apps/my-service/helm/values.yaml
          # Ensure git identity is always set even if secrets are blank
          git config user.name "${GITHUB_USER}"
          git config user.email "workflow@example.com"
          git commit -am "[workflow] update rollout image to {{inputs.parameters.imagetag}}"
          git remote set-url origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@${GIT_REMOTE}"
          git push origin HEAD:main
        env:
          - name: GITHUB_USER
            valueFrom:
              secretKeyRef:
                name: github-token
                key: username
          - name: GITHUB_EMAIL
            valueFrom:
              secretKeyRef:
                name: github-token
                key: email
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
          - name: GIT_REMOTE
            value: ${GIT_REMOTE} 
